### ISSUE TITLE
Issue with receiving real-time shadows

### ISSUE THREAD

**Issue by hemik1** [Kink3d/AnisotropicStandardShader#1]
Hey, I've grabbed your shader to try it out and found out it has an issue with receiving real-time shadows (unless I'm missing something).

Built-in Standard:
<img width="1431" alt="built-in standard" src="https://user-images.githubusercontent.com/22687633/27785017-86261c44-5fdc-11e7-9b88-05c5b47b0ca7.png">
Anisotropic Standard:
<img width="1436" alt="anisotropicstandard" src="https://user-images.githubusercontent.com/22687633/27785016-8601013e-5fdc-11e7-8998-9f8c6fc5e314.png">

**Comment by Kink3d** [comment]
Hi,

Thanks for the report. Should be fixed by latest commit (5a1979a60e2ec21dade30abdce97ab7ddc3b78b1)

Please let me know if this fixes your issue.

Thanks

**Comment by hemik1** [comment]
Hey, thanks for trying, but I'm sorry to say it's still the same for me. If you want a little bit more information, I'm running it in Unity 5.6.1f1, happens for both Forward and Deferred.

**Comment by Kink3d** [comment]
Hey,

Sorry for the lack of reply. What is your current build target? And if its iOS/Android what is the minimum OS level?
